In [1]:
pip install bqplot

Note: you may need to restart the kernel to use updated packages.


In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import ipywidgets
import bqplot
import numpy as np

In [2]:
f = pd.read_csv("C:/Users/sjnnt/is590dv/building_inventory.csv")
f

Agency Name  \
0      Department of Natural Resources   
1      Department of Natural Resources   
2      Department of Natural Resources   
3      Department of Natural Resources   
4      Department of Natural Resources   
5      Department of Natural Resources   
6      Department of Natural Resources   
7      Department of Natural Resources   
8      Department of Natural Resources   
9      Department of Natural Resources   
10     Department of Natural Resources   
11     Department of Natural Resources   
12     Department of Natural Resources   
13     Department of Natural Resources   
14     Department of Natural Resources   
15     Department of Natural Resources   
16     Department of Natural Resources   
17     Department of Natural Resources   
18     Department of Natural Resources   
19     Department of Natural Resources   
20     Department of Natural Resources   
21     Department of Natural Resources   
22     Department of Natural Resources   
23           Department of Corrections   
24        Department of Human Services   
25           Department of Corrections   
26        Department of Transportation   
27          Department of State Police   
28      Department of Military Affairs   
29           Department of Agriculture   
...                                ...   
8832      Department of Transportation   
8833      Department of Transportation   
8834      Department of Transportation   
8835      Department of Transportation   
8836      Department of Transportation   
8837      Department of Transportation   
8838      Department of Transportation   
8839      Department of Transportation   
8840      Department of Transportation   
8841      Department of Transportation   
8842      Department of Transportation   
8843      Department of Transportation   
8844      Department of Transportation   
8845      Department of Transportation   
8846      Department of Transportation   
8847      Department of Transportation   
8848      Department of Transportation   
8849    Department of Military Affairs   
8850      Department of Transportation   
8851      Department of Transportation   
8852      Department of Transportation   
8853      Department of Transportation   
8854      Department of Transportation   
8855      Department of Transportation   
8856      Department of Transportation   
8857      Department of Transportation   
8858      Department of Transportation   
8859      Department of Transportation   
8860  Illinois Community College Board   
8861    Department of Military Affairs   

                                          Location Name  \
0       Anderson Lake Conservation Area - Fulton County   
1       Anderson Lake Conservation Area - Fulton County   
2       Anderson Lake Conservation Area - Fulton County   
3       Anderson Lake Conservation Area - Fulton County   
4       Anderson Lake Conservation Area - Fulton County   
5       Anderson Lake Conservation Area - Fulton County   
6                Dixon Springs State Park - Pope County   
7                Dixon Springs State Park - Pope County   
8               Matthiessen State Park - LaSalle County   
9               Matthiessen State Park - LaSalle County   
10              Matthiessen State Park - LaSalle County   
11              Matthiessen State Park - LaSalle County   
12             Eldon Hazlet State Park - Clinton County   
13           Weinberg-King State Park - Schuyler County   
14           Weinberg-King State Park - Schuyler County   
15           Weinberg-King State Park - Schuyler County   
16           Weinberg-King State Park - Schuyler County   
17           Weinberg-King State Park - Schuyler County   
18           Weinberg-King State Park - Schuyler County   
19           Weinberg-King State Park - Schuyler County   
20           Weinberg-King State Park - Schuyler County   
21                                Wolf Creek State Park   
22                                Wolf Creek State Park   
23    

# Heat Map

In [3]:
f_g = f['Square Footage'].groupby([f['Agency Name'],f['Congress Dist']]).sum().reset_index(name = 'Total Square Footage')
f_g.head(10)

Agency Name  Congress Dist  \
0           Appellate Court / Fifth District             12   
1          Appellate Court / Fourth District             13   
2          Appellate Court / Second District              8   
3           Appellate Court / Third District             16   
4                   Chicago State University              1   
5                  Department of Agriculture             12   
6                  Department of Agriculture             13   
7                  Department of Agriculture             15   
8                  Department of Agriculture             17   
9  Department of Central Management Services              0   

   Total Square Footage  
0                 15124  
1                 16400  
2                 43330  
3                 18700  
4               1219492  
5                536232  
6               2000832  
7                 41984  
8                 29350  
9                231278

In [4]:
sf = f_g['Total Square Footage'].unique()
an = f_g['Agency Name'].unique()

cd = f_g['Congress Dist'].unique()
cd.sort()
cd

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18], dtype=int64)

Since the np.hist2d is only expecting numerical data, I manually construct a matrix for the weight values.

In [5]:
ft_sum = np.zeros([len(an),len(cd)])
for i,x in enumerate(an):
    for j,y in enumerate(cd):
        mask = ((f_g['Congress Dist'] == y) & (f_g['Agency Name'] == x))
        ft_sum[i,j] = f_g['Total Square Footage'][mask].sum()
ft_sum


array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.5124000e+04, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.6400000e+04, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.3330000e+04, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00,

In [6]:
ft_sum[ft_sum<=0] = np.nan
ft_sum=ft_sum.T
ft_sum

array([[          nan,           nan,           nan,           nan,
                  nan,           nan, 2.3127800e+05,           nan,
        3.7278400e+05,           nan,           nan, 4.0249000e+04,
                  nan,           nan, 8.2390000e+03, 5.5578000e+04,
        3.0000000e+03,           nan,           nan,           nan,
        3.8310000e+03,           nan,           nan,           nan,
                  nan, 5.6500000e+03, 3.1200000e+04,           nan,
                  nan, 4.1315000e+04,           nan,           nan,
                  nan,           nan,           nan],
       [          nan,           nan,           nan,           nan,
        1.2194920e+06,           nan,           nan,           nan,
        4.4954700e+05,           nan, 5.6458000e+05,           nan,
                  nan,           nan,           nan, 1.1814300e+05,
                  nan,           nan,           nan,           nan,
                  nan,           nan,           nan,          

In [8]:

x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()
col_sc = bqplot.ColorScale(scheme='RdPu',
                           min = np.nanmin(ft_sum),
                           max = np.nanmax(ft_sum))

x_ax = bqplot.Axis(scale=x_sc, label='Agency Name',label_offset = '20px',
                   tick_rotate = 45,tick_style = {'tick_offset':'100px','text_anchor':'top'})
y_ax = bqplot.Axis(scale=y_sc, label='Congress Dist',orientation='vertical')
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

In [9]:
heat_map = bqplot.GridHeatMap(color = ft_sum,
                              row =cd,column = an,
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'blue'})

fig = bqplot.Figure(marks = [heat_map], axes = [c_ax, y_ax, x_ax])
fig


Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(max=14695427.0, min=2364.0, scheme='RdPu'), si…

# Line plot

In [10]:
x_scl = bqplot.LinearScale()
y_scl = bqplot.LinearScale()

axl_x = bqplot.Axis(label='Year', scale=x_scl )
axl_y = bqplot.Axis( label='Total square footage', scale=y_scl, 
                    orientation='vertical',side ='left')

Since there are some dirty data in column "Year Acquired", I cleaned the data.

In [11]:
f_l = f['Square Footage'].groupby([f['Agency Name'],f['Congress Dist'],f['Year Acquired']]).sum().reset_index(name = 'Total Square Footage')
f_l = f_l[f_l['Year Acquired'] > 0]
f_l.head(10)


Agency Name  Congress Dist  Year Acquired  \
0    Appellate Court / Fifth District             12           1857   
1   Appellate Court / Fourth District             13           1967   
2   Appellate Court / Second District              8           1967   
3    Appellate Court / Third District             16           1858   
4    Appellate Court / Third District             16           1860   
6            Chicago State University              1           1873   
7            Chicago State University              1           1970   
8            Chicago State University              1           1971   
9            Chicago State University              1           1972   
10           Chicago State University              1           1973   

    Total Square Footage  
0                  15124  
1                  16400  
2                  43330  
3                  15000  
4                   3700  
6                  11000  
7                 183964  
8                  70995  
9                  49841  
10                426197

In [12]:
print(len(an),len(cd))
print(ft_sum.shape)

35 19
(19, 35)


In [13]:
i,j = 0,11
mask_l = (f_l['Agency Name'].values == an[j]) & (f_l['Congress Dist'].values == cd[i])

In [14]:
line_plot = bqplot.Lines(x = f_l['Year Acquired'][mask_l],
                         y = f_l['Total Square Footage'][mask_l],
                        scales = {'x':x_scl, 'y':y_scl})
fig = bqplot.Figure(marks = [line_plot], axes=[axl_x, axl_y])
fig

Figure(axes=[Axis(label='Year', scale=LinearScale(), side='bottom'), Axis(label='Total square footage', orient…

# put them together

In [15]:
def get_data_value(change):
    # to make sure we only support single selections
    if len(change['owner'].selected) == 1: # *only* 1 selection
        i,j = change['owner'].selected[0]
        v = ft_sum[i,j]
        mySelectedLabel.value = 'Total Square Footages = ' + str(v)
        # UPDATE LINE PLOT TOO
        agen_n =an[j]
        cong_d = cd[i]
        mask_l = (f_l['Agency Name'].values == an[j]) & (f_l['Congress Dist'].values == cd[i])

        line_plot.x = f_l['Year Acquired'][mask_l]
        line_plot.y = f_l['Total Square Footage'][mask_l]
          
# make sure we "observe" for a change in our heatmap (traitlets)
heat_map.observe(get_data_value, 'selected')

In [16]:
fig_heatmap = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
fig_lines = bqplot.Figure(marks=[line_plot], axes=[axl_x, axl_y])

In [17]:
mySelectedLabel = ipywidgets.Label()
fig_heatmap.layout.min_width='600px'
fig_lines.layout.min_width = '400px'

plots = ipywidgets.HBox([fig_heatmap, fig_lines])
myDashboard = ipywidgets.VBox([mySelectedLabel, plots])
myDashboard

# Can you keep the x and y ranges static on the line plot?

To keep the x and y ranges static on the line plot, we should set up the minimum and the maximum of the x scale and y scale.

In [18]:
x_scl = bqplot.LinearScale(min = min(f_l['Year Acquired']), max = max(f_l['Year Acquired']))
y_scl = bqplot.LinearScale(min = min(f_l['Total Square Footage']), max = max(f_l['Total Square Footage']) )

axl_x = bqplot.Axis(label='Year', scale=x_scl )
axl_y = bqplot.Axis( label='Total square footage', scale=y_scl, 
                    orientation='vertical',side ='left')

In [19]:
i,j = 0,11
mask_l = (f_l['Agency Name'].values == an[j]) & (f_l['Congress Dist'].values == cd[i])

In [20]:
line_plot_sta = bqplot.Lines(x = f_l['Year Acquired'][mask_l],
                         y = f_l['Total Square Footage'][mask_l],
                        scales = {'x':x_scl, 'y':y_scl} )
fig = bqplot.Figure(marks = [line_plot_sta], axes=[axl_x, axl_y])
fig

Figure(axes=[Axis(label='Year', scale=LinearScale(max=2019.0, min=1753.0), side='bottom'), Axis(label='Total s…

In [21]:
def get_data_value_sta(change):
    # to make sure we only support single selections
    if len(change['owner'].selected) == 1: # *only* 1 selection
        i,j = change['owner'].selected[0]
        v = ft_sum[i,j]
        mySelectedLabel.value = 'Total Square Footages = ' + str(v)
        # UPDATE LINE PLOT TOO
        agen_n =an[j]
        cong_d = cd[i]
        mask_l = (f_l['Agency Name'].values == an[j]) & (f_l['Congress Dist'].values == cd[i])

        line_plot_sta.x = f_l['Year Acquired'][mask_l]
        line_plot_sta.y = f_l['Total Square Footage'][mask_l]
          
# make sure we "observe" for a change in our heatmap (traitlets)
heat_map.observe(get_data_value_sta, 'selected')

In [22]:
fig_heatmap = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
fig_lines = bqplot.Figure(marks=[line_plot_sta], axes=[axl_x, axl_y])

In [23]:
mySelectedLabel = ipywidgets.Label()
fig_heatmap.layout.min_width='600px'
fig_lines.layout.min_width = '400px'

plots = ipywidgets.HBox([fig_heatmap, fig_lines])
myDashboard = ipywidgets.VBox([mySelectedLabel, plots])
myDashboard

Change the color of the line.

In [19]:
line_plot_sta.colors =['red']